### ISSUE TITLE
indexeddb lib link 404

### ISSUE THREAD

**Issue by caryoscelus** [rowtype-yoga/.github#2]
i've followed [discussion about purs indexeddb bindings](https://github.com/truqu/purescript-indexedDB/pull/7) to find this organization (definitely going to check out more of your stuff!) and the only link related to indexeddb is https://github.com/rowtype-yoga/purescript-y-indexeddb, but it leads nowhere

**Comment by i-am-the-slime** [comment]
@caryoscelus It leads somewhere for me now. Is it still broken for you?

**Comment by caryoscelus** [comment]
@i-am-the-slime [still broken](https://archive.is/GSdAd) . could it be a private repository ?

**Comment by i-am-the-slime** [comment]
Good catch, didn't think of that. I made it public!
